name: wormhole
adopt-info: wormhole
summary: get things from one computer to another, safely
description: |
  This package provides a library and a command-line tool named wormhole, which
  makes it possible to get arbitrary-sized files and directories (or short
  pieces of text) from one computer to another. The two endpoints are identified
  by using identical "wormhole codes": in general, the sending machine generates
  and displays the code, which must then be typed into the receiving machine.
base: core24
platforms:
  amd64:
  arm64:
  armhf:
  ppc64el:
  riscv64:
  s390x:
grade: stable
confinement: strict

apps:
  wormhole:
    command: bin/wormhole
    plugs:
      - network
      - network-bind
      - home
      - removable-media

parts:
  wormhole:
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(python3 -c "import versioneer; print(versioneer.get_version())")
    plugin: python
    source: https://github.com/warner/magic-wormhole.git
    source-type: git
    build-environment:
      - CRYPTOGRAPHY_DONT_BUILD_RUST: "1"
    build-packages:
      - libffi-dev
      - libssl-dev
      - libsodium-dev
      - rust-all
      - pkg-config
